---
apiVersion: v1
kind: Namespace
metadata:
  name: $APP_MESH_NS
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $APP_MESH_CONTROLLER_NAME  
  namespace: $APP_MESH_NS
  annotations:
    eks.amazonaws.com/role-arn: $APP_MESH_ROLE_ARN
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $APP_MESH_CONTROLLER_NAME
  namespace: $APP_MESH_NS
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: $APP_MESH_CONTROLLER_NAME
  namespace: $APP_MESH_NS
subjects:
- kind: ServiceAccount
  name: $APP_MESH_CONTROLLER_NAME
roleRef:
  kind: Role
  name: $APP_MESH_CONTROLLER_NAME
  apiGroup: rbac.authorization.k8s.io