---
apiVersion: v1
kind: Namespace
metadata:
  name: $KONG_NS
  labels:
    mesh: $DEMO_APP_MESH_NAME
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: $KONG_NS
  namespace: $KONG_NS
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: $KONG_NS
  listeners:
    - portMapping:
        port: 80
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: $DEMO_APP_SVC_1
          namespace: $AWS_DEFAULT_PROFILE
    - virtualService:
        virtualServiceRef:
          name: $DEMO_APP_SVC_2
          namespace: $AWS_DEFAULT_PROFILE
  serviceDiscovery:
    dns:
      hostname: $KONG_NS-$KONG_NS-proxy.$KONG_NS.svc.cluster.local