apiVersion: v1
kind: Namespace
metadata:
  name: ${AWS_DEFAULT_PROFILE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEMO_APP_NAME
  namespace: $AWS_DEFAULT_PROFILE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEMO_APP_NAME}
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ${DEMO_APP_NAME}
        version: v1
    spec:
      containers:
        - name: ${DEMO_APP_NAME}
          image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/echo-server:1.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "country"
              value: "Echo Server is up!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEMO_APP_SVC_1}-v1
  namespace: $AWS_DEFAULT_PROFILE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $DEMO_APP_SVC_1
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: $DEMO_APP_SVC_1
        version: v1
    spec:
      containers:
        - name: ${DEMO_APP_SVC_1}
          image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/echo-server:1.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "country"
              value: "${DEMO_APP_SVC_1}-v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEMO_APP_SVC_2}-v1
  namespace: $AWS_DEFAULT_PROFILE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $DEMO_APP_SVC_2
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: $DEMO_APP_SVC_2
        version: v1
    spec:
      containers:
        - name: $DEMO_APP_SVC_2
          image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/echo-server:1.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "country"
              value: "${DEMO_APP_SVC_2}-v1"
---
apiVersion: v1
kind: Service
metadata:
  name: $DEMO_APP_NAME
  namespace: $AWS_DEFAULT_PROFILE
  labels:
    app: $DEMO_APP_NAME
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: $DEMO_APP_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: ${DEMO_APP_SVC_1}-v1
  namespace: $AWS_DEFAULT_PROFILE
  labels:
    app: $DEMO_APP_SVC_1
    version: v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: $DEMO_APP_SVC_1
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: ${DEMO_APP_SVC_2}-v1
  namespace: $AWS_DEFAULT_PROFILE
  labels:
    app: $DEMO_APP_SVC_2
    version: v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: $DEMO_APP_SVC_2
    version: v1
---